# Generated by Django 5.1.1 on 2024-09-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_author', models.CharField(max_length=200)),
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
