# Generated by Django 5.1.1 on 2024-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feedback_text',
            field=models.CharField(max_length=800),
        ),
    ]
